name = "clear-view-pressure-washing"
compatibility_date = "2026-08-01"
pages_build_output_dir = "dist"

# Copy this file to wrangler.toml to run `npm run dev` locally.
[[d1_databases]]
binding = "DB"
database_name = "clearview-leads"
database_id = "4b086ac0-0c13-4e63-b112-f69715106b19"
