/**
 * Clear View - brand file generator
 * -----------------------------------------------------------------------------
 * Builds the whole logo family from the single traced mark so the variants can
 * never drift apart. Re-run after scripts/trace-logo.mjs.
 *
 *   node scripts/build-brand.mjs
 *
 * Emits into assets/brand/:
 *   logo-mark.svg          icon only (written by trace-logo.mjs)
 *   logo-stacked.svg       mark over wordmark - matches the client's artwork
 *   logo-lockup.svg        horizontal, for headers and letterheads
 *   logo-mono-reverse.svg  single-ink version for dark grounds / one-colour print
 *   sprite.svg             the mark as a <symbol>, for inlining in the page
 *
 * The wordmark is set in <text>. For print or sign-writing handoff, open a
 * lockup in a vector editor and convert the type to outlines.
 */
import { readFile, writeFile } from 'node:fs/promises';

const BRAND = '#2E6DA4';   // logo blue, sampled from the supplied artwork
const INK   = '#0A1626';   // navy, sampled from the supplied artwork
const BONE  = '#E9F1F8';
const MUTED = '#A4BCD1';
const FONT  = "Geist, ui-sans-serif, system-ui, 'Segoe UI', Arial, sans-serif";

const src = await readFile('assets/brand/logo-mark.svg', 'utf8');
const d = src.match(/ d="([^"]+)"/)[1];
const vb = src.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/);
const MW = parseFloat(vb[1]);   // 100
const MH = parseFloat(vb[2]);   // ~44.87

const header = (name) => `<?xml version="1.0" encoding="UTF-8"?>
<!-- Clear View - ${name}. Generated by scripts/build-brand.mjs from the traced
     mark in logo-mark.svg. Edit the generator, not this file. -->`;

/* ---- stacked: matches the arrangement of the client's own artwork -------- */
{
  /* 10 units of side padding so the mark never runs edge to edge, and type
     sized to sit inside the box rather than overflow it. */
  const PAD = 10, W = MW + PAD * 2, H = MH + 35;
  const svg = `${header('STACKED LOCKUP (primary)')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"
     role="img" aria-label="Clear View Pressure Washing and Auto Detail">
  <g transform="translate(${PAD} 0)">
    <path fill="${BRAND}" fill-rule="evenodd" d="${d}"/>
  </g>
  <text x="${W / 2}" y="${MH + 18}" fill="${INK}" text-anchor="middle" font-family="${FONT}"
        font-size="15" font-weight="700" letter-spacing="-0.2">CLEAR VIEW</text>
  <text x="${W / 2}" y="${MH + 28.5}" fill="${INK}" text-anchor="middle" font-family="${FONT}"
        font-size="4.4" font-weight="400" letter-spacing="0.6">PRESSURE WASHING &amp; AUTO DETAIL</text>
</svg>
`;
  await writeFile('assets/brand/logo-stacked.svg', svg);
}

/* ---- stacked, reversed for dark grounds --------------------------------- */
{
  const PAD = 10, W = MW + PAD * 2, H = MH + 35;
  const svg = `${header('STACKED LOCKUP, REVERSED (for navy grounds)')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"
     role="img" aria-label="Clear View Pressure Washing and Auto Detail">
  <g transform="translate(${PAD} 0)">
    <path fill="${BRAND}" fill-rule="evenodd" d="${d}"/>
  </g>
  <text x="${W / 2}" y="${MH + 18}" fill="#FFFFFF" text-anchor="middle" font-family="${FONT}"
        font-size="15" font-weight="700" letter-spacing="-0.2">CLEAR VIEW</text>
  <text x="${W / 2}" y="${MH + 28.5}" fill="${MUTED}" text-anchor="middle" font-family="${FONT}"
        font-size="4.4" font-weight="400" letter-spacing="0.6">PRESSURE WASHING &amp; AUTO DETAIL</text>
</svg>
`;
  await writeFile('assets/brand/logo-stacked-reverse.svg', svg);
}

/* ---- horizontal lockup --------------------------------------------------- */
{
  const markH = 42;
  const markW = (MW / MH) * markH;         // preserve the mark's aspect
  const scale = markH / MH;
  const textX = markW + 16;
  const W = 268, H = 60;
  const svg = `${header('HORIZONTAL LOCKUP')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"
     role="img" aria-label="Clear View Pressure Washing and Auto Detail">
  <g transform="translate(0 ${(H - markH) / 2}) scale(${scale.toFixed(4)})">
    <path fill="${BRAND}" fill-rule="evenodd" d="${d}"/>
  </g>
  <text x="${textX.toFixed(1)}" y="32" fill="${INK}" font-family="${FONT}"
        font-size="23" font-weight="700" letter-spacing="-0.25">CLEAR VIEW</text>
  <text x="${(textX + 1).toFixed(1)}" y="45" fill="${INK}" font-family="${FONT}"
        font-size="7.2" font-weight="400" letter-spacing="1.28" opacity=".72">PRESSURE WASHING &amp; AUTO DETAIL</text>
</svg>
`;
  await writeFile('assets/brand/logo-lockup.svg', svg);
}

/* ---- mono / one-colour --------------------------------------------------- */
{
  const markH = 42;
  const markW = (MW / MH) * markH;
  const scale = markH / MH;
  const textX = markW + 16;
  const W = 268, H = 60;
  const svg = `${header('MONO / REVERSE LOCKUP - single ink, for dark grounds, one-colour print, vinyl and embroidery')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}"
     color="${BONE}" role="img" aria-label="Clear View Pressure Washing and Auto Detail">
  <g transform="translate(0 ${(H - markH) / 2}) scale(${scale.toFixed(4)})">
    <path fill="currentColor" fill-rule="evenodd" d="${d}"/>
  </g>
  <text x="${textX.toFixed(1)}" y="32" fill="currentColor" font-family="${FONT}"
        font-size="23" font-weight="700" letter-spacing="-0.25">CLEAR VIEW</text>
  <text x="${(textX + 1).toFixed(1)}" y="45" fill="currentColor" font-family="${FONT}"
        font-size="7.2" font-weight="400" letter-spacing="1.28" opacity=".7">PRESSURE WASHING &amp; AUTO DETAIL</text>
</svg>
`;
  await writeFile('assets/brand/logo-mono-reverse.svg', svg);
}

/* ---- favicon source: the mark on navy, padded to a square ---------------- */
{
  const pad = 14;
  const S = MW + pad * 2;
  const y = (S - MH) / 2;
  const svg = `${header('FAVICON SOURCE - mark on navy, squared')}
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${S} ${S}" width="${S}" height="${S}"
     role="img" aria-label="Clear View">
  <rect width="${S}" height="${S}" rx="${(S * 0.18).toFixed(1)}" fill="${INK}"/>
  <g transform="translate(${pad} ${y.toFixed(2)})">
    <path fill="${BRAND}" fill-rule="evenodd" d="${d}"/>
  </g>
</svg>
`;
  await writeFile('assets/brand/favicon-source.svg', svg);
}

/* ---- sprite symbol, for inlining once in the page ------------------------ */
{
  const svg = `${header('SPRITE - the mark as a symbol, inlined once in index.html')}
<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">
  <symbol id="cv-mark" viewBox="0 0 ${MW} ${MH}">
    <path fill="currentColor" fill-rule="evenodd" d="${d}"/>
  </symbol>
</svg>
`;
  await writeFile('assets/brand/sprite.svg', svg);
}

console.log('brand files written (mark viewBox 0 0 ' + MW + ' ' + MH + ')');
